// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrRjOZhaw5U_UVCOAX8-wfzaBt7I4n8Q',
    appId: '1:644096454105:web:f9498fb36d2996b591fdc8',
    messagingSenderId: '644096454105',
    projectId: 'testflutter-65a05',
    authDomain: 'testflutter-65a05.firebaseapp.com',
    storageBucket: 'testflutter-65a05.appspot.com',
    measurementId: 'G-WM9Y0S2YTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyxVhrv4ka3HRZWsEDVBdFbVvaN02f1k',
    appId: '1:644096454105:android:8a41ce115f78759591fdc8',
    messagingSenderId: '644096454105',
    projectId: 'testflutter-65a05',
    storageBucket: 'testflutter-65a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXzR6Gki29Og5YHTNC-fWJbEWzRuCOHg',
    appId: '1:644096454105:ios:dac9935fdb5a0b4291fdc8',
    messagingSenderId: '644096454105',
    projectId: 'testflutter-65a05',
    storageBucket: 'testflutter-65a05.appspot.com',
    androidClientId: '644096454105-dv4n2ltdgprtv04ctgmg70fp99rd1qb1.apps.googleusercontent.com',
    iosClientId: '644096454105-cfhn2bg8b3flqfhrq32osqgeso81ekdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXzR6Gki29Og5YHTNC-fWJbEWzRuCOHg',
    appId: '1:644096454105:ios:2cd7a7190a01702491fdc8',
    messagingSenderId: '644096454105',
    projectId: 'testflutter-65a05',
    storageBucket: 'testflutter-65a05.appspot.com',
    androidClientId: '644096454105-dv4n2ltdgprtv04ctgmg70fp99rd1qb1.apps.googleusercontent.com',
    iosClientId: '644096454105-53pc7tbrmp73vbdl800i0h5c9b0pp7nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLogin.RunnerTests',
  );
}
